### ISSUE TITLE
Remove path-dirname and bump major

### ISSUE THREAD

**Issue by phated** [gulpjs/glob-parent#23]
@paulmillr I'm about to head out for the night after I publish glob-parent 4.0.0 but I'll get path-dirname removed tomorrow and bump the major.

**Comment by paulmillr** [comment]
@phated ping

**Comment by phated** [comment]
Planning to do this today after [the stream](https://www.twitch.tv/events/wL8RryzwQ5637gCJFkAZcw)

**Comment by phated** [comment]
Just published 5.0.0 which drops support for any node <6 - I kept 6 around because our devDeps support it and it's not actually EOL until April 30th.

**Comment by paulmillr** [comment]
yay! thank you!
