### ISSUE TITLE
Ability to avoid autoreplace \\ in patterns even on Windows

### ISSUE THREAD

**Issue by mrmlnc** [gulpjs/glob-parent#24]
I have one pattern that uses escaping for parenthesis:

```
file-\\(suffix\\).md
```

As a result of the work I get:

```js
globParent('file-\\(suffix\\).md')
// file-

// expected result: .
```

Obviously, this is an incorrect parent directory. Yeap, I understand that this is described in the documentation, but I find it difficult to get all users to use the new format. Also I see no reason to change user input inside my package, because it can lead to problems.

Maybe we can add an option to control automatic replacement?

https://github.com/gulpjs/glob-parent/blob/d4975484222bb811c02dc2dc268ea48e2fb7ae6d/index.js#L15-L17

Found this issue in https://github.com/mrmlnc/fast-glob/issues/223. The `fast-glob` package [only accepts patterns with forward slashes](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows).

**Comment by phated** [comment]
This is definitely something we can look into. How would you feel about adding an options object and an option to disable that? I'm thinking the option makes sense so we can have backwards compatibility but maybe it's time to drop the replacement hack. I'm not sure.

**Comment by mrmlnc** [comment]
IMHO, I would prefer to remove this hack. However, this is a major change for gulp users.

**Comment by phated** [comment]
@mrmlnc looks great! Please send a PR. I will release a minor version with that change and then we can drop the hack all together in a major.
