### ISSUE TITLE
SNYK ReDoS vulnerability

### ISSUE THREAD

**Issue by rhuddleston** [gulpjs/glob-parent#28]
We were notified of this Snyk finding and CVE:

https://snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905

I didn't see an open issue on this yet, any thoughts on a potential fix?

**Comment by phated** [comment]
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Are you looking to sponsor gulpjs project maintenance?

**Comment by rhuddleston** [comment]
Wow okay, didn't realize this was a touchy subject

**Comment by phated** [comment]
If you'd read the issue template, we are quite clear.

 If you'd spend the money you're giving snyk to actually pay the maintainers you bother, it might be a different story.

**Comment by rhuddleston** [comment]
the other template said "Dependency vulnerability", this wasn't a dependency issue. Also I just asked if you had any plans. If your answer was no then there we might have tried to submit a pull request or something, was simply asking.
