### ISSUE TITLE
Possible Regular expresion denial of service vulnerability. 

### ISSUE THREAD

**Issue by TannerS** [gulpjs/glob-parent#45]
I think this is the right library and right repo, I seen this while getting reports and wanted to point it out just in case it was not brought up before. If I am wrong then please close this. 

![image](https://user-images.githubusercontent.com/8866319/121602009-4a4e5d00-ca0c-11eb-9f84-797b3842e30f.png)

**Comment by phated** [comment]
Already solved in glob-parent 5.1.1 and 6.0.0 - look at the changelog before you open an issue.
