### ISSUE TITLE
Security vulnerability report

### ISSUE THREAD

**Issue by RunDevelopment** [gulpjs/glob-parent#48]
Hello,

On June 11, I sent a report of a security vulnerability I found to security@tidelift.com in accordance with the security policy of this project. On their [Security process page](https://docs.tidelift.com/article/51-security-process), Tidelift says that "the Tidelift security team will reply to the reporter within two business days to acknowledge receipt". Tidelift has yet to respond back to me.

For this reason, I now opened this issue. Who can I contact to report the security vulnerability I found?

**Comment by phated** [comment]
Please continue to reach out through that channel.
