### ISSUE TITLE
npm audit - Vulnerabilities Observed in dependent package 

### ISSUE THREAD

**Issue by deepakb2410** [gulpjs/glob-parent#50]
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular expression denial of service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ glob-parent                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.1.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-htmlhint [dev]                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-htmlhint > htmlhint > parse-glob > glob-base >          │
│               │ glob-parent                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1751                            │

**Comment by phated** [comment]
https://overreacted.io/npm-audit-broken-by-design/
